views/home.py
# -*- coding: utf-8 -*-
import random
from models import accessControl, global_v
from flask import Blueprint, app, render_template, request, session, redirect, url_for, jsonify

index = Blueprint('index', __name__)

@index.route('/login', methods=['GET', 'POST'])
def login():

    error = None
    if not request.form['username']:
        error = 'username is null'
        return render_template('login.html', error = error)
    if not request.form['password']:
        error = 'password is null'
        return render_template('login.html', error = error)


    username = request.form['username'].encode('utf8')
    password = request.form['password'].encode('utf8')
    user=None
    if username == "admin":
        user = accessControl.verify(username, password)
    else:
        er = accessControl._valid_login_format(username,password)
        if er:
            return render_template('login.html', error = er)

        user = accessControl.verify(username, password)


    if user is None:
        error = 'username and password does not match'
        return render_template('login.html', error = error)
    else:
        if user.type == 1:
            session['type'] = 1
            session['username'] = username
            return redirect(url_for('index.show_network',username=username))
        if user.status == 0:
            error = 'User account is locked'
            return render_template('login.html', error = error)
        session['type'] = 0
        session['username'] = username
        if not user.questions:
            return render_template('select.html',questions = global_v.fixed_questions)
        else:
              ques=user.questions
              list=[ques.sq1,ques.sq2,ques.sq3]
              #  get count from webpage , send list[index_list[count]]
              # correct answer =  verifyQues(index_list[count], session['username'])
              return render_template('validate.html', questions = list, check = 1)
        #return redirectork(url_for('index.show_network', username = username))

@index.route('/logout')
def logout():
    # remove the username from the session if it's there
    session.pop('username', None)
    return render_template('login.html')

@index.route('/show_network/<username>')
def show_network(username):
    return render_template('Test.html', username = username)

@index.route('/Insert_SecureQuestions')
def Insert_SecureQuestions():
    a = request.args.get('a', 0, type=str)
    b = request.args.get('b', 0, type=str)
    c = request.args.get('c', 0, type=int)
    print c
    global_v.q_a.append(a)
    global_v.q_a.append(b)

    if c == 3:
        accessControl.createSecQues(global_v.q_a, session['username'])
        for i in global_v.q_a:
            del i

    c += 1
    print a, b
    return jsonify(result=c)

@index.route('/validate')
def validate():
    q = request.args.get('a', 0, type = str)
    index = request.args.get('c', 0, type = int)
    answer = request.args.get('b', 0, type = str)
    check = request.args.get('check', 0, type = int)
    index += 1
    re = accessControl.verifyQues(index, session['username'], answer)
    if re:
        return jsonify(result = 1, check =check)
    else:
        return jsonify(result = 0, check =check)

@index.route('/changePassword')
def change_password():
    a = request.args.get('a', 0, type = str)
    b = request.args.get('b', 0, type = str)
    username = session['username']
    print username,a,b
    re = accessControl.verify(username, a)
    msg = None
    if re:
        msg = accessControl.change_pwd(username, b)
        if msg == None:
            msg = 'success'
    else:
        msg = 'Old password wrong!'
    print msg
    return jsonify(result = msg)

@index.route('/jumpAdminPage')
def jump_admin_page():
    accounts = accessControl.get_all_users()
    return render_template('admin.html',accounts=accounts)

@index.route('/jumpRegister')
def jump_register():
    return render_template('register.html')

@index.route('/jumpChangePwd')
def jump_change_pwd():
    return render_template('changePassword.html')

@index.route('/jumpChangeSec')
def jump_security_questions():
    return render_template('changeSecurityQuestion.html')

@index.route('/jumpValidate')
def jump_validate():
    username = session['username']
    questions = accessControl.get_security_question(username)
    list = [questions.sq1, questions.sq2, questions.sq3]
    return render_template('validate.html', check = 0, questions = list)

@index.route('/getSecurityQuestions')
def get_security_questions():
    username = session['username']
    questions = accessControl.get_security_question(username)

    return jsonify(questions = global_v.fixed_questions, question1 = questions.sq1, question2 = questions.sq2,
                   question3 = questions.sq3)

@index.route('/changeSecureQuestions')
def change_secure_questions():
    username = session['username']
    q1 = request.args.get('a', 0, type = str)
    a1 = request.args.get('b', 0, type = str)
    q2 = request.args.get('c', 0, type = str)
    a2 = request.args.get('d', 0, type = str)
    q3 = request.args.get('e', 0, type = str)
    a3 = request.args.get('f', 0, type = str)
    c1 = request.args.get('check1', 0, type = int)
    c2 = request.args.get('check2', 0, type = int)
    c3 = request.args.get('check3', 0, type = int)
    print c1, c2, c3
    re1 = 1
    re2 = 1
    re3 = 1
    if c1 != 0 or a1!="":
        re1 = accessControl.change_security_question(1, q1, a1, username)
    if c2 != 0 or a2!="":
        re2 = accessControl.change_security_question(2, q2, a2, username)
    if c3 != 0 or a3 != "":
        re3 = accessControl.change_security_question(3, q3, a3, username)
    if re1>0 and re2>0 and re3>0:
        return jsonify(result = 1)
    else:
        return jsonify(result = 0)



# input list should be in format of: [ username,pwd,type,status,fname,lname]
@index.route('/createAccount',methods=['GET', 'POST'])
def create_account():
    #
    user=[]
    print 'hello'
    username = request.args.get('c', 0, type = str)
    pwd = request.args.get('d', 0, type = str)
    fname = request.args.get('a', 0, type = str)
    lname = request.args.get('b', 0, type = str)
    print username
    user.append(username)
    user.append(pwd)
    user.append(0)
    user.append(1)
    user.append(fname)
    user.append(lname)
    error = None
    # user=User('username',0,1, fname, fname,pwd)
    result=accessControl.createAccount(user)
    if not result == None:
        return jsonify(err =result[0])
    else:
        return jsonify(err = '')


@index.route('/deleteAccount')
def delete_account():
    username = request.args.get('username', 0, type = str)
    print username
    accessControl.delete_user(username)
    return jsonify()

views/network.py
# -*- coding: utf-8 -*-
import json
from operator import methodcaller
from models import netModel,global_v,SendMessage
from flask import Blueprint, app, render_template, request, session, jsonify

network = Blueprint('network', __name__)



@network.route('/whole_network')
def return_whole_network():
    ran = global_v.ran
    net = netModel.return_json()

    return jsonify(result1=net, ranNum = ran)

@network.route('/addNode')
def add_node():
    a = request.args.get('a',0,type = str)
    node = json.loads(a)
    pid = node['pid']
    index = node['index']
    nid = netModel.add_node(pid, index)
    return jsonify(result1 = nid)

@network.route('/addPattern')
def add_pattern():
    a = request.args.get('a',0,type = str)
    b = request.args.get('b',0,type = int)
    ps = json.loads(a)
    re = netModel.add_pattern(ps,b)
    return jsonify(result1= re[0], result2 = re[1])


@network.route('/addDomain')
def add_domain():
    a = request.args.get('a',0,type = str)
    ds = json.loads(a)
    re = netModel.add_domain(ds)
    return jsonify(result1= re[1], result2 = re[2],result3 =re[0], result4=re[3])


@network.route('/deleteNode')
def delete_node():
    a = request.args.get('a', 0, type = str)
    nodes = json.loads(a)
    netModel.delete_node(nodes)
    return jsonify()

@network.route('/deletePattern')
def delete_pattern():
    a = request.args.get('a', 0, type = str)
    nodeId = json.loads(a)
    print nodeId
    did = nodeId['did']
    pid = nodeId['pid']
    if did != -1:
        netModel.delete_domain(pid, did)
    else:
        netModel.delete_pattern(pid)
    return jsonify()

@network.route('/activeNode')
def active_node():
    nid = int(request.args.get('a', 0, type = str))
    netModel.change_node_status(nid, 1)
    msg_list= SendMessage.get_resend_msg_list(nid)
    return jsonify(result = msg_list)

@network.route('/addConnection')
def add_connection():
    a = request.args.get('a', 0, type = str)
    b = request.args.get('b', 0, type = str)
    nid1 = int(a)
    nid2 = int(b)
    netModel.add_connection(nid1,nid2)
    return jsonify()

@network.route('/deleteConnection')
def delete_connection():
    a = request.args.get('a', 0, type = str)
    b = request.args.get('b', 0, type = str)
    nid1 = int(a)
    nid2 = int(b)
    netModel.delete_connection(nid1,nid2)
    return jsonify()

views/test.py
from models import accessControl
from models import netModel
from models import mydb
import json
from models import Node




u = 'ew'.encode('utf8')
p = 'dsa'.encode('utf8')
re = accessControl.verify(u, p)
print re


# u = User('s','d','ds')
#
# p = Pattern(2,u)
#
# print p.connect.name

mydb.insert_db('update ')
print accessControl._valid_login_format('spike1390', '2cs744')
# l = [Node(21,4,3), Node(1,2,5), Node(2,4,2)]
# l.sort()
# for u in l:
#     print u.index
# re = accessControl.verify('spikewang', 'cs744')
# print re.name



r2 = accessControl.verify('spikewang', 'cs7dsd44')
# print r2.name

ps = netModel.return_net()

lis = [2,3,4]
for i in range(0,len(lis)):
    print lis[i]

print json.dumps(ps, default = methodcaller("json"))

a = 96
dis_string = []
for p in ps:
    tmp_str = ''
    print p.id
    if len(p.nodes) == 1:
        tmp_str = '%s%s'% (chr(a+p.id),p.nodes[0].id)
    else:
        length = len(p.nodes)
        for i in range(0, length):
            for j in range(i,length):
                index1 = p.nodes[i].index
                index2 = p.nodes[j].index
                if index2 == 2*index1:
                    tmp_str = tmp_str + '%s%s--%s%s;'%(chr(a+p.id),p.nodes[i].id,chr(a+p.id), p.nodes[j].id)
                if index2 == 2*index1+1:
                    tmp_str = tmp_str + '%s%s--%s%s;'%(chr(a+p.id),p.nodes[i].id, chr(a+p.id),p.nodes[j].id)

    if len(tmp_str) != 0 and tmp_str[len(tmp_str)-1] == ';':
        tmp_str = tmp_str[:-1]
    dis_string.append(tmp_str)

print dis_string
print json.dumps(dis_string)
    # json_string = json.dumps([ob.__dict__ for ob in p.nodes])
    #
    # print json_string

templates/admin.html
<!--
    Created by yun on 3/28/16.
    Author:yun
-->
<html>
<head>
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">


    <style type="text/css">
        body{
            font-family: "Hiragino Sans GB","Microsoft YaHei","微软雅黑",tahoma,arial,simsun,"宋体" !important;
            color: #555;
            font-size: 13px;
            margin: 0;
            padding: 0;
        }
        button:focus{
            outline: none;
        }
        .navi-header{
        /*transition:all ease-in-out 0.3s;*/
        font-family: 'IM Fell French Canon SC', serif;
        height: 60px;
        background: rgba(255,255,255,0.97);
        opacity: 0.93;
        padding: 0;
        z-index: 9;
        width: 100%;
        border-bottom: 1px solid #E2E2E2;
        box-shadow: 0 1px 4px rgba(0, 0, 0, 0.1),0 0 0 1px rgba(0, 0, 0, 0.05);
    }
    .navi-header a{
        color:#66615b;
        font-size: 14px;
        text-decoration: none;
    }
    .navi-inner{
        width: 1300px;
        text-align: left;
        height: 68px;
        margin: 0 auto;
        padding: 0;
            }
    .navi-logo{
        float: left;
        width:125px;
        margin-left: 65px;
        margin-top: 18px;
        margin-right: 10px;
        height:60px;
    }
    .navi-logo a{
        font-family: 'Kavoon', cursive;
        font-size: 20px;
        color: #D15600;
        margin-left: -15px;
    }

    .navi-entry{
       float: right;
       margin: auto  0;
       margin-right: 30px;
    }
    .navi-entry li {
     display: inline-block;
     margin:  28px 45px 24px 20px;
    }

        .messageBoxBlock {
          font-family: "Helvetica Neue", Helvetica, Arial;
          font-size: 14px;
          line-height: 20px;
          font-weight: 400;
          color: #3b3b3b;
          -webkit-font-smoothing: antialiased;
          font-smoothing: antialiased;
          margin-top: 100px;
          margin-left: 370px;
        }

        .messageBox{
            max-height: 550px;
            overflow-y:auto;
            scrollbar-face-color: #ebebeb;
            scrollbar-shadow-color: #ffffff;
            scrollbar-highlight-color:#ffffff;
            scrollbar-3dlight-color: #d8d8d8;
            scrollbar-darkshadow-color: #d8d8d8;
            scrollbar-track-color:#ffffff;
            scrollbar-arrow-color: #686868;
        }

        .table {
          box-shadow: 0 1px 1px rgba(0, 0, 0, 0.2);
          display: table;
          border-radius: 5px;
            max-width: 800px;
        }


        .row {
          display: table-row;
          background: #f6f6f6;
        }
        .row:nth-of-type(odd) {
          background: #e9e9e9;
        }
        .row.header {
          font-weight: 900;
          color: #ffffff;
          background: #ea6153 !important;
          border-top-left-radius: 5px;
          border-top-right-radius: 5px;
        }
        .row.green {
          background: #27ae60;
        }
        .row.blue {
          background: #2980b9;
        }

        .cell {
          padding: 15px 30px;
          display: table-cell;
        }

        .row:hover{
            background: #98d0e0;
            color: white;
        }
        .select-btn2:hover{
            color: #2980b9;
        }
        .select-btn{
            color: #fc6355;
        }
        .select-btn:hover{
            color: red;
        }
    </style>
</head>
<body>
<div id="navi-header" class="navi-header ">
	<div class="navi-inner">
		<div id="navi-logo" class="navi-logo">
             <a href="{{ url_for('index.show_network',username = session.username) }}">Tree Network</a>
		</div>

		<ul class="navi-entry">
            <li class="entry-home-li">

                <a href="##" class="entry-home">
					<span class="home-icon">
					</span>
					<span class="home-text">{{ session.username }}</span>
				</a>
			</li>
			<li class="entry-signout-li">
				<a href="{{ url_for("index.logout") }}" class="entry-signout">
					<span class="signout-icon"></span>
					<span class="signout-text">SignOut</span>
				</a>
			</li>
		</ul>

	</div>
</div>


<div class="messageBoxBlock table wrapper">
    <div class="messageBox">
            <div class="row header blue">
          <div class="cell">
            Username
          </div>
          <div class="cell">
            FirstName
          </div>
            <div class="cell">
            LastName
          </div>
          <div class="cell">
            Password
          </div>
          <div class="cell">
            <i style="font-size: 25px;cursor: pointer;margin-top: -10px;position: relative;top:7px" class="material-icons select-btn2" >add</i>
          </div>
        </div>

        {% for account in accounts %}
        <div class="row">
          <div class="cell">{{ account.name }}</div>
          <div class="cell">{{ account.fname }}</div>
          <div class="cell">{{ account.lname }}</div>
          <div class="cell">************</div>
          <div class="cell">
            <i  style="font-size: 25px;cursor: pointer;margin-top: -10px;position: relative;top:6px" class="material-icons select-btn" >clear</i>
          </div>
        </div>
        {% endfor %}

    </div>
</div>
    <script type="text/javascript">
        var $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
        $('.select-btn2').click(function(){
            window.location.href='{{  url_for("index.jump_register") }}';
        });
         $('.select-btn').click(function(){
             var username = $(this).parent().parent().find('.cell').first().text();
             console.log(username);
             $.getJSON($SCRIPT_ROOT + '/home/deleteAccount', {
                username:username
              }, function(data) {
             });
             $(this).parent().parent().remove();
        });
    </script>
</body>

templates/index.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <a href="{{ url_for('network.return_whole_network') }}">go</a>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Blog</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='login.css') }}">
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:100,300,400,700">
    <link href='https://fonts.googleapis.com/css?family=Crimson+Text:400,700italic' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
<link href="http://s3.amazonaws.com/codecademy-content/courses/ltp2/css/bootstrap.min.css" rel="stylesheet">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>
<body>


<div class="NetTitle">
    <p> Tree Network </p>
</div>

<form class="login-form" action="{{  url_for("index.login") }}" method="post">
  <p class="login-text">
    <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fa fa-lock fa-stack-1x"></i>
    </span>
  </p>
  <input  name="username" class="login-username" autofocus="true" required="true" placeholder="Username" />
  <input type="password"   name="password" class="login-password" required="true" placeholder="Password" />
  <input type="submit" name="Login" value="Login" class="login-submit btn-login" />

</form>
{% if error %}<div class="error_account"><strong>Error:</strong> {{ error }} </div>{% endif %}

<div class="slider">
  <div class="slide slide-feature1 active-slide"></div>
</div>
</body>
<script type="text/javascript">
{#    var main = function() {#}
{#      setInterval(function() {#}
{#            var currentSlide = $(".active-slide");#}
{#            var nextSlide = $(".active-slide").next();#}
{#            if (nextSlide.length === 0) {#}
{#                nextSlide = $(".slide").first();#}
{#            }#}
{#        currentSlide.fadeOut(3000).removeClass("active-slide");#}
{#        nextSlide.fadeIn(3500).addClass("active-slide");#}
{#      }, 3000);#}
{#    };#}

</script>
</html>

templates/register.html
<!--
    Created by yun on 3/28/16.
    Author:yun
-->
<html>
<head>
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">


    <style type="text/css">
        body{
            font-family: "Hiragino Sans GB","Microsoft YaHei","微软雅黑",tahoma,arial,simsun,"宋体" !important;
            color: #555;
            font-size: 13px;
            margin: 0;
            padding: 0;
        }
        button:focus{
            outline: none;
        }
        .navi-header{
            /*transition:all ease-in-out 0.3s;*/
            font-family: 'IM Fell French Canon SC', serif;
            height: 60px;
            background: rgba(255,255,255,0.97);
            opacity: 0.93;
            padding: 0;
            z-index: 9;
            width: 100%;
            border-bottom: 1px solid #E2E2E2;
            box-shadow: 0 1px 4px rgba(0, 0, 0, 0.1),0 0 0 1px rgba(0, 0, 0, 0.05);
        }
    .navi-header a{
        color:#66615b;
        font-size: 14px;
        text-decoration: none;
    }
    .navi-inner{
        width: 1300px;
        text-align: left;
        height: 68px;
        margin: 0 auto;
        padding: 0;
            }
    .navi-logo{
        float: left;
        width:125px;
        margin-left: 65px;
        margin-top: 18px;
        margin-right: 10px;
        height:60px;
    }
    .navi-logo a{
        font-family: 'Kavoon', cursive;
        font-size: 20px;
        color: #D15600;
        margin-left: -15px;
    }

    .navi-entry{
       float: right;
       margin: auto  0;
       margin-right: 30px;
    }
    .navi-entry li {
     display: inline-block;
     margin:  28px 45px 24px 20px;
    }


    /* head over*/

    /*	container begin*/
    .container {
        margin:0 auto;
        border: 1px solid #e1e8ed;
        height:650px;
        width: 888px;
        background-clip: padding-box;
        border-radius: 8px;
        margin-top: 30px;
    }

    .container2 {
        width: 600px;
        clear: both;
        margin: 0 auto 10px;
    }

    .col-xs-10>h1{
        padding: 40px 0 20px 0;
        font-size: 21px;
        line-height: .8;
        text-rendering: optimizeLegibility;
        color: #D15600;
    }

    .textbox{
        padding: 3px 0;
        font-size: 12px;
    }

    .prompt{
        margin-top: 40px;
        font-size: 15px;
    }
    .prompt input {
        width: 450px;
        transition: background .2s linear;
        display: inline-block;
        padding: 4px;
        margin: 0;
        outline: 0;
        background-color: #fff;
        border: 1px solid #e1e8ed;
        border-radius: 3px;
        font-size: 13px;
        line-height: 20px;
        margin-top: 5px;
        height: 35px;
    }

    input:focus{
    outline: 0;
    color: #292f33;
    border-color: #56b4ef;
    }

    .submit-button{
        margin:  30px auto;
         margin-left:  220px;
        text-decoration: none;
        padding: 0 11px;
        line-height: 22px;
        border-width: 0;
        color: #fff;
        border-radius: 4px;
        transition: .2s ease;
        text-align: center;
        border-color: #137ec6;
        border-top-color: #1992da;
        border-bottom-color: #0d6ab2;
        background: linear-gradient(#3baee7, #08c);
        font-size: 13px;
        height: 30px;
    }
    .submit-button2{
        padding: 4px 8px;
        margin-top: 5px;
         background: #ebebeb;
		  color: #888;
		  text-shadow: -1px -1px 2px #f8f8f8;
            width: 110px;
            height: 30px;
            border: none;
            border-radius: 4px;
        font-size: 13px;
    }
    .submit-button:hover{
        background: linear-gradient(#4ab4e8, #1491d0);
    }
    .submit-button:active{
        background: linear-gradient(#1b9dde, #006da3);
    }
    .errorMsg{
        font-size: 12px;
        color: #D15600;
        width: 0;
        position: relative;
        top:5px;
        left: 20px;
        height: 15px;
    }
    </style>
</head>
<body>
<div id="navi-header" class="navi-header ">
	<div class="navi-inner">
		<div id="navi-logo" class="navi-logo">
             <a href="{{ url_for('index.show_network',username = session.username) }}">Tree Network</a>
		</div>

		<ul class="navi-entry">
            <li class="entry-home-li">

                <a href="##" class="entry-home">
					<span class="home-icon">
					</span>
					<span class="home-text">{{ session.username }}</span>
				</a>
			</li>
			<li class="entry-signout-li">
				<a href="{{ url_for("index.logout") }}" class="entry-signout">
					<span class="signout-icon"></span>
					<span class="signout-text">SignOut</span>
				</a>
			</li>
		</ul>

	</div>
</div>

<div class="container">
    	<div class="container2">
	    	<div class="row">
	    		<div class="col-xs-1"></div>
	    		<div class="col-xs-10">
                    <h1 class="errortitle">Create Account</h1>
	    			<form id="register-form" >
	    				<div class="textbox">
	    					<div class="prompt name">
	    						<label for="full-name" class="text-label field-name">First name</label>
	    						<div>
	    							<input type="text" name="fname" id="first-name" autocomplete="off" maxlength="20">
	    						</div>
                                 <label class="errorMsg " for="error"></label>
	    					</div>
	    					<div class="prompt email">
	    						<label for="email-adress" class="text-label email-address">Last Name</label>
	    						<div>
	    							<input type="text" name="lname" id="last-name" autocomplete="off" maxlength="20">
	    						</div>
                                <label class="errorMsg" for="error"></label>
	    					</div>
	    					<div class="prompt username">
	    						<label for="type-username" class="text-label type-username">Username</label>
	    						<div>
	    							<input type="text" name="username" id="username" autocomplete="off" maxlength="20">
	    						</div>
                                <label class="errorMsg" for="error"></label>
	    					</div>
                            <div class="prompt password">
	    						<label for="creat-password" class="text-label creat-password">Password</label>
	    						<div>
	    							<input type="password" name="pwd" id="password" autocomplete="off" maxlength="20">
	    						</div>
                                <label class="errorMsg" for="error"></label>
	    					</div>
	    				</div>
	    				<div class="submit-signup">
                            <input type="button" class="submit-button2" name="submit_button" value="Cancel">
	    					<input type="button" class="submit-button" name="submit_button" value="Create Account">
	    				</div>
	    			</form>
	    		</div>
	    		<div class="col-xs-1"></div>
	    	</div>
		</div>
	</div>
     <script type="text/javascript">
         var checkOrNot = false;
         var $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
        $('.submit-button2').click(function(){
            window.location.href='{{  url_for("index.jump_admin_page") }}';
        });

        $('[name=fname]').blur(function(){
            var value = $(this).val();
            var label = $(this).parent().next();
            if(value==""){
                checkOrNot = false;
                label.text('First Name can not be empty').animate({
                                    width: '500px'
                                }, 500, function () {

                                });
            }
            else{
                checkOrNot=true;
                label.text("").css('width','0');
            }
        });

         $('[name=lname]').blur(function(){
            var value = $(this).val();
            var label = $(this).parent().next();
            if(value==""){
                checkOrNot = false;
                label.text('Last Name can not be empty').animate({
                                    width: '500px'
                                }, 500, function () {

                                });
            }
            else{
                checkOrNot=true;
                label.text("").css('width','0');
            }
        });

        function checkUsername(str){
            if(!( (str[0]>='A'&&str[0]<='Z') || (str[0]>='a'&&str[0]<='z') )){
                return -1;
            }
            for(var i in str){
                if(!( (str[i]>='A'&&str[i]<='Z') || (str[i]>='a'&&str[i]<='z') || (str[i]>='0'&&str[i]<='9') )){
                    return -2;
                }
            }
            return 1;
        }

        function  checkCharacter(ch){
           var  specialChar=["!","@","#","$","%","^","&","*","?"];
           for(var i in specialChar){
               if(specialChar[i]==ch) return true;
           }
           return false;
        }

        function checkPassword(str){
            for(var i in str){
                if(!( (str[i]>='A'&&str[i]<='Z') || (str[i]>='a'&&str[i]<='z') || (str[i]>='0'&&str[i]<='9')
                        || checkCharacter(str[i]) )){
                    return false;
                }
            }
            return true;
        }

        $('[name=username]').blur(function(){
            var value = $(this).val();
            var label = $(this).parent().next();
            if(value.length<6){
                checkOrNot = false;
                label.text('The length of username must be at least six characters').animate({
                                    width: '500px'
                                }, 500, function () {

                                });
            }
            else if(checkUsername(value)==-1){
                checkOrNot = false;
                label.text('The first character of a username must be an alphabet').animate({
                                    width: '500px'
                                }, 500, function () {

                                });
            }
            else if(checkUsername(value)==-2){
                checkOrNot = false;
                label.text('Username can only have number and alphabet!').animate({
                                    width: '500px'
                                }, 500, function () {

                                });
            }
            else{
                checkOrNot=true;
                label.text('').css('width','0');
            }
        });


        $('[name=pwd]').blur(function(){
            var value = $(this).val();
            var label = $(this).parent().next();
            if(value.length<6){
                checkOrNot = false;
                label.text('The length of password must be at least six characters').animate({
                                    width: '500px'
                                }, 500, function () {

                                });
            }
            else if(!checkPassword(value)){
                checkOrNot = false;
                label.text('Unrecognized special characters').animate({
                                    width: '500px'
                                }, 500, function () {

                                });
            }
            else{
                checkOrNot=true;
                label.text('').css('width','0');
            }
        });

        $(function() {
                 var submit_form = function(e) {
                     if(!checkOrNot) return false;
                  $.getJSON($SCRIPT_ROOT + '/home/createAccount', {
                        a: $('[name=fname]').val(),
                        b: $('[name=lname]').val(),
                        c: $('[name=username]').val(),
                        d: $('[name=pwd]').val()
                  }, function(data) {
                      var err = data.err;
                      if(err == ""){
                          window.location.href='{{  url_for("index.show_network",username=session['username']) }}';
                      }
                      else{
                          $('[name=username]').parent().next().text(err).animate({
                                    width: '500px'
                                }, 500, function () {
                                });
                          $('[name=pwd]').val("");
                      }
                  });
                  return false;
                };
                $('.submit-button').bind('click', submit_form);
    		});

    </script>
</body>